:REPOS_URL: https://github.com/kazurayam/TS2307error-caused-by-the-main-field-in-package.config-in-monorepo
:BRANCH_URL: ${REPOS_URL}/blob/main
:DOC_URL: https://kazurayam.github.io/TS2307error-caused-by-the-main-field-in-package.config-in-monorepo

= package.jsonファイルのmainフィールドの値が原因でTS2307 "Cannot find module" エラーが発生した件

== 環境

- OS: macOS Sequoia 15.7.2
- ランタイム: bun 1.3.6

== 背景

わたしは link:https://bun.com/[bun] でTypeScriptでHonoを使ったプロジェクトを開発する技法を学習しているところだ。その一貫でQiita記事 link:https://qiita.com/mtfuji_ksk/items/5da28a1f4fabfa994246[「Hono + Zod-OpenAPIで快適に開発する」 @mtfuji_ksk] のサンプルコードを写経しようと決めた。

この記事は複数のフロントエンドとしてのパッケージとバックエンドとしてのパッケージからなるプロジェクトを想定すると述べている。そしてHonoとZod-OpenAPIを使うTypeScriptコードをどう書くべきかを解説している。ところが複数パッケージをどうやって構築するかについて具体的な方法を述べていない。技術的に別の話題だから著者は一つの話題に絞って記述したのだろう。もっともなことと思う。ところがわたしがいざサンプルコードを写経しようとしたら、パッケージの構築法を具体的に選んでプロジェクトを構成しなければならない。さもないとTypeScriptのコードを書く作業を始められなかった。どうしようか？

わたしはこのプロジェクトを一つのGitレポジトリの中に複数のパッケージを格納する構成すなわち「モノレポ」にすることにした。そのためにbunの link:https://bun.com/docs/pm/workspaces[Workspaces] を適用することにした。

== 問題発生

TODO

== 解決方法

TODO

== 詳しい説明

=== モノレポの構成を作る

==== ROOTディレクトリを作る

適当なディレクトリを作成してそこにcdする。例えば `ts2307error-in-monorepo` という名前のディレクトリを作成したとしよう。

[source,shell]
----
$ mkdir ts2307error-in-monorepo
$ cd ts2307error-in-monorepo
$ ROOT=$(pwd)
----

このディレクトリの中にプロジェクトを作成する。この後の文の中でこのディレクトリのパスを `$ROOT` という記号で表すことにする。

==== bun init する

bunのinitコマンドを使ってプロジェクトを初期化した。

[source,shell]
----
$ cd $ROOT
$ bun init -y
----

==== パッケージのディレクトリを作る

`packages/backend` ディレクトリと `packages/shared` ディレクトリを作った。
[source,shell]
----
$ cd $ROOT
$ mkdir packages
$ mkdir packages/backend
$ mkdir packages/frontend
$ mkdir pacages/shared
----

`packages/backed` ディレクトリの中で bun init コマンドを実行してパッケージを初期化した。`frontend` と `shared` も同様にした。

[source, shell]
----
$ cd $ROOT/package/backend
$ bun init -y
...
$ cd $ROOT/package/frontend
$ bun init -y
...
$ cd $ROOT/package/shared
$ bun init -y
...
----

こんなツリーができた。

[source,shell]
----
$ tree -L 3 .
.
├── bun.lock
├── CLAUDE.md
├── index.ts
├── node_modules
├── package.json
├── packages
│   ├── backend
│   │   ├── bun.lock
│   │   ├── CLAUDE.md
│   │   ├── index.ts
│   │   ├── node_modules
│   │   ├── package.json
│   │   ├── README.md
│   │   └── tsconfig.json
│   ├── frontend
│   │   ├── bun.lock
│   │   ├── CLAUDE.md
│   │   ├── index.ts
│   │   ├── node_modules
│   │   ├── package.json
│   │   ├── README.md
│   │   └── tsconfig.json
│   └── shared
│       ├── bun.lock
│       ├── CLAUDE.md
│       ├── index.ts
│       ├── node_modules
│       ├── package.json
│       ├── README.md
│       └── tsconfig.json
├── README.md
└── tsconfig.json
----

==== $ROOT/package.json を編集してworkspacesを宣言した

`$ROOT/package.json` ファイルを編集して `workspaces` フィールドを指定して、`packages` フォルダの下にあるすべてのディレクトリをパッケージとすることを宣言した。

[source,json]
----
include::../package.json[]
----

==== 各パッケージの `package.json` を修正した。

`packages/shared/package.json` ファイルを編集した。bun init コマンドで自動生成されたコードはこうだった。

[source,json]
----
{
  "name": "shared",
  "module": "index.ts",
  "type": "module",
  ...
----

これをわたしは書き換えた。こんなふうに。

[source,json]
----
{
  "name": "@kazurayam/ts2307error-in-monorepo-shared",
  "main": "./index.ts",
  "type": "module",
  ...
----

1. `name` フィールドの値を `shared` から `@kazurayam/ts2307error-in-monorepo-shared` に書き換えた。これがパッケージの名前となる。`"names": "shared"` とするとディレクトリ名とパッケージ名が同じになってしまって、紛らわしい。少し冗長で説明的なパッケージ名の方がいいと考えた。
2. `module` フィールドを削除し、代わりに `main` フィールドを追加した。bun initコマンドが`package.json` の中に `module` フィールドを生成したのだが、これって **bunのバグ** なのではないか？ Nodeの link:https://nodejs.org/api/packages.html#nodejs-packagejson-field-definitions[公式ドキュメント Node.js package.json field definitions] には `module` フィールドが無い。だから `"main"` フィールドに取り替えた。

同じ考えを `$ROOT/packages/backend/packages.json` と `$ROOT/packages/frontend/packages.json` に適用し、修正した。

=== Qiita記事のTypeScriptコードを写した

オリジナルQiita記事 link:https://qiita.com/mtfuji_ksk/items/5da28a1f4fabfa994246[「Hono + Zod-OpenAPIで快適に開発する」 @mtfuji_ksk] のサンプルコードを写した。オリジナルQiita記事は `shared/schema.ts` のように `src` ディレクトリを持たないパスにしていたが、わたしは `src` を導入し `shared/src/schema.ts` とした。好みの問題である。

- link:${BRANCH_URL}/packages/shared/src/schema.ts[$ROOT/packages/shared/src/schema.ts]
- link:${BRANCH_URL}/packages/backend/src/route/user.ts[$ROOT/packages/backend/src/user.ts]
- link:${BRANCH_URL}/packages/backend/src/server.ts[$ROOT/packages/backend/src/server.ts] /* Qiita記事は `index.ts` と名付けていたが `server.ts` と改名した。好みの問題 */
- link:${BRANCH_URL}/packages/frontend/src/api/client.ts[$ROOT/packages/frontend/src/api/client.ts]
- link:${BRANCH_URL}/packages/frontend/src/components/UserList.tsx[$ROOT/packages/frontend/src/components/UserList.tsx]

これらのTypeScriptコードはオリジナルQiita記事からのコピペである。ただし `import` 文のパスはわたしのプロジェクト構成に合わせて書き換えた。

=== bun install を実行した

`$ROOT` ディレクトリで `bun install` コマンドを実行した。

[source,shell]
----
$ cd $ROOT
$ bun install --linker isolated
...
----

これにより各パッケージの依存関係が解決され `node_modules` フォルダが作成された。

[source,shell]
----
$ cd $ROOT
$ tree -L 3
.
├── bun.lock
├── CLAUDE.md
├── index.ts
├── node_modules
│   ├── @types
│   │   └── bun -> ../.bun/@types+bun@1.3.6/node_modules/@types/bun
│   └── typescript -> .bun/typescript@5.9.3/node_modules/typescript
├── package.json
├── packages
│   ├── backend
│   │   ├── bun.lock
│   │   ├── CLAUDE.md
│   │   ├── index.ts
│   │   ├── node_modules    <!-- 依存関係が解決されてできた -->
│   │   ├── package.json
│   │   ├── README.md
│   │   ├── src
│   │   └── tsconfig.json
│   ├── frontend
│   │   ├── bun.lock
│   │   ├── CLAUDE.md
│   │   ├── index.ts
│   │   ├── node_modules    <!-- 依存関係が解決されてできた -->
│   │   ├── package.json
│   │   ├── README.md
│   │   ├── src
│   │   └── tsconfig.json
│   └── shared
│       ├── bun.lock
│       ├── CLAUDE.md
│       ├── index.ts
│       ├── node_modules    <!-- 依存関係が解決されてできた -->
│       ├── package.json
│       ├── README.md
│       ├── src
│       └── tsconfig.json
├── README.md
└── tsconfig.json
----

特に `$ROOT/packages/backend/node_modules` ディレクトリ を取り上げて中身を見てみるとこうだ。

[source,shell]
----
$ cd $ROOT
$ tree ./packages/backend/node_modules
./packages/backend/node_modules
├── @types
│   └── bun -> ../../../../node_modules/.bun/@types+bun@1.3.6/node_modules/@types/bun
└── typescript -> ../../../node_modules/.bun/typescript@5.9.3/node_modules/typescript
----

あれえ！変だなあ。@kazurayam/ts2307error-in-monorepo-shared ディレクトリがあるはずなのだが、無いぞ。

[source,shell]
----
$ cd $ROOT/packages/frontend
$ bun add react
$ bun add @types/react
----

